# Generated by Django 4.2.20 on 2025-08-29 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('identification_number', models.CharField(max_length=20, unique=True, verbose_name='Cédula/RIF')),
                ('primary_phone', models.CharField(blank=True, max_length=15, verbose_name='Teléfono Principal')),
                ('secondary_phone', models.CharField(blank=True, max_length=15, verbose_name='Teléfono Secundario')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Límite de Crédito')),
                ('status', models.BooleanField(default=True, verbose_name='Estado Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100, verbose_name='Nombre de la Empresa')),
                ('rnc', models.CharField(max_length=13, verbose_name='RNC')),
                ('nombre_contacto', models.CharField(max_length=100, verbose_name='Nombre del Contacto')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('pais', models.CharField(choices=[('DO', 'República Dominicana'), ('US', 'Estados Unidos'), ('PR', 'Puerto Rico'), ('HT', 'Haití'), ('JM', 'Jamaica'), ('CU', 'Cuba'), ('CO', 'Colombia'), ('VE', 'Venezuela'), ('PA', 'Panamá'), ('CR', 'Costa Rica'), ('MX', 'México'), ('CN', 'China'), ('KR', 'Corea del Sur'), ('TW', 'Taiwán')], default='DO', max_length=2, verbose_name='País')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('categoria', models.CharField(choices=[('smartphones', 'Smartphones'), ('accesorios', 'Accesorios'), ('repuestos', 'Repuestos'), ('tablets', 'Tablets'), ('smartwatch', 'Smartwatch'), ('audio', 'Audio y Auriculares'), ('cargadores', 'Cargadores y Cables'), ('fundas', 'Fundas y Protectores')], max_length=20, verbose_name='Categoría de Productos')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección Completa')),
                ('terminos_pago', models.CharField(blank=True, choices=[('contado', 'Contado'), ('15-dias', '15 días'), ('30-dias', '30 días'), ('45-dias', '45 días'), ('60-dias', '60 días')], max_length=20, null=True, verbose_name='Términos de Pago')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Límite de Crédito (RD$)')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('activo', models.BooleanField(default=True, verbose_name='Suplidor Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre_empresa'],
            },
        ),
        migrations.CreateModel(
            name='EntradaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(editable=False, max_length=20, unique=True)),
                ('numero_factura', models.CharField(max_length=50)),
                ('fecha_entrada', models.DateField(default=django.utils.timezone.now)),
                ('ncf', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('marca', models.CharField(choices=[('apple', 'Apple'), ('samsung', 'Samsung'), ('xiaomi', 'Xiaomi'), ('huawei', 'Huawei'), ('lg', 'LG'), ('motorola', 'Motorola'), ('nokia', 'Nokia'), ('sony', 'Sony'), ('google', 'Google'), ('oneplus', 'OnePlus'), ('oppo', 'Oppo'), ('vivo', 'Vivo'), ('realme', 'Realme'), ('tecno', 'Tecno'), ('infinix', 'Infinix'), ('alcatel', 'Alcatel'), ('zte', 'ZTE'), ('otros', 'Otros')], max_length=20)),
                ('modelo', models.CharField(max_length=100)),
                ('capacidad', models.CharField(blank=True, choices=[('16', '16GB'), ('32', '32GB'), ('64', '64GB'), ('128', '128GB'), ('256', '256GB'), ('512', '512GB'), ('1t', '1TB')], max_length=10, null=True)),
                ('imei_serial', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado'), ('reacondicionado', 'Reacondicionado'), ('exhibicion', 'Exhibición')], max_length=20)),
                ('color', models.CharField(blank=True, choices=[('negro', 'Negro'), ('blanco', 'Blanco'), ('azul', 'Azul'), ('rojo', 'Rojo'), ('dorado', 'Dorado'), ('plateado', 'Plateado'), ('verde', 'Verde'), ('morado', 'Morado'), ('rosa', 'Rosa'), ('gris', 'Gris'), ('otros', 'Otros')], max_length=20, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('cantidad_minima', models.PositiveIntegerField(default=2, verbose_name='Cantidad Mínima')),
                ('costo_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_itbis', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('monto_itbis', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margen_ganancia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.proveedor')),
            ],
            options={
                'verbose_name': 'Entrada de Producto',
                'verbose_name_plural': 'Entradas de Productos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'db_table': 'caja',
            },
        ),
    ]
