# Generated by Django 4.2.20 on 2025-08-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_movimientostock'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaproducto',
            name='es_producto_base',
            field=models.BooleanField(default=False, verbose_name='Es producto base'),
        ),
    ]
