# Generated by Django 4.2.20 on 2025-09-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_cuentaporcobrar_pagocuentaporcobrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='productos',
            field=models.TextField(blank=True, verbose_name='Productos de la Venta'),
        ),
    ]
