# Generated by Django 4.2.20 on 2025-09-03 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_cuentaporcobrar_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_efectivo_real', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_tarjeta_real', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_esperado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.caja')),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
                'db_table': 'cierre_caja',
            },
        ),
    ]
