# Generated by Django 4.2.20 on 2025-09-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_cierrecaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cuota_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='es_financiada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venta',
            name='interes_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_financiado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='plazo_meses',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='venta',
            name='tasa_interes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='venta',
            name='total_con_interes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
