# Generated by Django 4.2.20 on 2025-09-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_venta_cuota_mensual_venta_es_financiada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='montoinicial',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
    ]
