# Generated by Django 4.2.20 on 2025-09-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_devolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='total_a_pagar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
