# Generated by Django 4.2.20 on 2025-09-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0012_venta_total_a_pagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='anulada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='monto_total_con_interes',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Monto Total con Interés'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('vencida', 'Vencida'), ('pagada', 'Pagada'), ('parcial', 'Pago Parcial'), ('anulada', 'Anulada')], default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Total Original'),
        ),
    ]
