# Generated by Django 4.2.20 on 2025-09-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0013_cuentaporcobrar_anulada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='monto_total_con_interes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Total con Interés'),
        ),
    ]
