# Generated by Django 4.2.20 on 2025-09-19 22:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0014_alter_cuentaporcobrar_monto_total_con_interes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_comprobante', models.CharField(max_length=20, unique=True, verbose_name='Número de Comprobante')),
                ('tipo_comprobante', models.CharField(choices=[('recibo', 'Recibo de Pago'), ('comprobante', 'Comprobante de Pago')], default='recibo', max_length=15)),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes_pago', to='facturacion.cliente')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='facturacion.cuentaporcobrar')),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='facturacion.pagocuentaporcobrar')),
            ],
            options={
                'verbose_name': 'Comprobante de Pago',
                'verbose_name_plural': 'Comprobantes de Pago',
                'db_table': 'comprobantes_pago',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
