# Generated by Django 4.2.20 on 2025-09-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0015_comprobantepago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='entradaproducto',
            name='marca',
            field=models.CharField(choices=[('honda', 'Honda'), ('yamaha', 'Yamaha'), ('suzuki', 'Suzuki'), ('kawasaki', 'Kawasaki'), ('tvs', 'TVS'), ('hero', 'Hero'), ('loncin', 'Loncin'), ('kove', 'Kove'), ('x1000', 'X1000'), ('ktm', 'KTM'), ('bajaj', 'Bajaj'), ('otros', 'Otros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='pais',
            field=models.CharField(choices=[('DO', 'República Dominicana'), ('US', 'Estados Unidos'), ('PR', 'Puerto Rico'), ('HT', 'Haití'), ('JM', 'Jamaica'), ('CU', 'Cuba'), ('CO', 'Colombia'), ('VE', 'Venezuela'), ('PA', 'Panamá'), ('CR', 'Costa Rica'), ('MX', 'México'), ('CN', 'China'), ('KR', 'Corea del Sur'), ('TW', 'Taiwán'), ('JP', 'Japón')], default='DO', max_length=2, verbose_name='País'),
        ),
    ]
