# Generated by Django 4.2.20 on 2025-09-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0016_remove_proveedor_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='interes_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
