# Generated by Django 4.2.20 on 2025-09-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0017_venta_interes_mensual'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='eliminada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
