# Generated by Django 4.2.20 on 2025-09-26 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturacion', '0018_cuentaporcobrar_eliminada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantepago',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comprobantepago',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprobantepago',
            name='motivo_anulacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprobantepago',
            name='usuario_anulacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_anulados', to=settings.AUTH_USER_MODEL),
        ),
    ]
