# Generated by Django 4.2.20 on 2025-09-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0019_comprobantepago_anulado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocuentaporcobrar',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
    ]
