# Generated by Django 4.2.20 on 2025-09-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0020_pagocuentaporcobrar_anulado'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaproducto',
            name='numero_maquina',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número/Máquina'),
        ),
    ]
