# Generated by Django 4.2.20 on 2025-10-05 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0021_entradaproducto_numero_maquina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='descuento_porcentaje',
        ),
    ]
