# Generated by Django 4.2.20 on 2025-12-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0023_venta_descuento_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantepago',
            name='tipo_comprobante',
            field=models.CharField(choices=[('recibo', 'Recibo de Pago'), ('comprobante', 'Comprobante de Pago'), ('descuento', 'Comprobante de Descuento')], default='recibo', max_length=15),
        ),
    ]
