# Generated by Django 4.2.20 on 2025-12-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0024_alter_comprobantepago_tipo_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='plazo_meses',
            field=models.IntegerField(default=1, verbose_name='Plazo en meses'),
        ),
    ]
